version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: alura_receita
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
